 Exception Handling (Banking System)

In [ ]:
def withdraw_amount():
    try:
        amount = input("Enter the amount you want to withdraw: ")

        # Check if numeric
        if not amount.replace('.', '', 1).isdigit():
            raise ValueError("Invalid input. Please enter a numeric value.")

        amount = float(amount)
        if amount <= 0:
            raise ValueError("Withdrawal amount must be greater than zero.")

        print(f"Successfully withdrawn: {amount}")

    except ValueError as ve:
        print(f"ValueError: {ve}")
    except TypeError:
        print("TypeError: Invalid data type entered.")

withdraw_amount()

Exception Handling with File & Data Processing

In [1]:

def calculate_average_marks():
    marks_list = [85, "90", "abc", None, 75, "100", "N/A", 95]
    valid_marks = []

    for mark in marks_list:
        try:
            valid_marks.append(float(mark))
        except (ValueError, TypeError):
            print(f"Skipping invalid entry: {mark}")

    if valid_marks:
        average = sum(valid_marks) / len(valid_marks)
        print(f"Average of valid marks: {average}")
    else:
        print("No valid marks found.")

calculate_average_marks()

Skipping invalid entry: abc
Skipping invalid entry: None
Skipping invalid entry: N/A
Average of valid marks: 89.0

OOP (Library Management System)

In [2]:
class Book:
    def __init__(self, title, author):
        self.title = title
        self.author = author
        self.is_available = True

    def borrow_book(self):
        if self.is_available:
            self.is_available = False
            print(f"You have borrowed '{self.title}'")
        else:
            print(f"'{self.title}' is currently not available.")

    def return_book(self):
        self.is_available = True
        print(f"You have returned '{self.title}'")

# Example usage
book1 = Book("Python Basics", "John Smith")
book1.borrow_book()
book1.borrow_book()  # Trying to borrow again
book1.return_book()
book1.borrow_book()

You have borrowed 'Python Basics'
'Python Basics' is currently not available.
You have returned 'Python Basics'
You have borrowed 'Python Basics'

 OOP (Inheritance and Polymorphism â€“ Animal Shelter)

In [3]:
class Animal:
    def make_sound(self):
        pass

class Dog(Animal):
    def make_sound(self):
        return "Woof!"

class Cat(Animal):
    def make_sound(self):
        return "Meow!"

class Bird(Animal):
    def make_sound(self):
        return "Chirp!"

# Polymorphism demonstration
animals = [Dog(), Cat(), Bird()]
for animal in animals:
    print(animal.make_sound())

Woof!
Meow!
Chirp!

 NumPy (Array Operations)

In [4]:
import numpy as np

# 2D array: Rows = Cities, Columns = Temperatures (e.g., daily/weekly)
temperatures = np.array([
    [30, 32, 31],
    [25, 28, 26],
    [35, 36, 34]
])

# Maximum temperature in each city
max_per_city = np.max(temperatures, axis=1)
print("Max temperature per city:", max_per_city)

# Average temperature across all cities
overall_avg = np.mean(temperatures)
print("Overall average temperature:", overall_avg)

# Cities with temps above overall average
cities_above_avg = temperatures[np.any(temperatures > overall_avg, axis=1)]
print("Cities with temperatures above average:\n", cities_above_avg)

Max temperature per city: [32 28 36]
Overall average temperature: 30.77777777777778
Cities with temperatures above average:
 [[30 32 31]
 [35 36 34]]

NumPy (Broadcasting & Conditional Update)

In [6]:
import numpy as np

def apply_below_average_discount(sales: np.ndarray, discount_rate: float = 0.1) -> np.ndarray:

    avg = np.mean(sales)
    mask = sales < avg
    sales[mask] *= (1 - discount_rate)
    return sales

# Example usage:
monthly_sales = np.array([1200.0, 950.0, 1300.0, 800.0, 1100.0, 1000.0,
                          1400.0, 900.0, 1250.0, 1050.0, 1150.0, 980.0])

updated = apply_below_average_discount(monthly_sales, discount_rate=0.1)
print("Updated sales:", updated)

Updated sales: [1200.  855. 1300.  720. 1100.  900. 1400.  810. 1250.  945. 1150.  882.]